### ISSUE TITLE
the single example provided in the readme calls an undefined method

### ISSUE THREAD

**Issue by robokaso** [rtbhouse-apps/rtbhouse-php-sdk#6]
`PHP Fatal error:  Uncaught Error: Call to undefined method RTBHouse\ReportsApi\ReportsApiSession::getCampaignStatsTotal()`

**Comment by kamilglod** [comment]
@robokaso thanks for your note, and sorry for the late reply. 
I just changed README (https://github.com/rtbhouse-apps/rtbhouse-php-sdk/commit/cd67a7a4fcda25d75bed435ac2b595a301141ee3) to workable version.
